- name: Search for latest version of RHEL 7 AMI
  ec2_ami_facts:
    region: "{{ region }}"
    owner: "{{owner}}"
    filters:
      name: "{{ find_image }}"
  register: ami_results

#- debug: var=ami_results

- name: Search for subnet ids
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
  register: subnet_ids

#- debug: var=subnet_ids

- name: Create a new security group
  ec2_group:
    name: "{{ sg_name }}"
    description: Group created by AWS playbook
    region: "{{ region }}"
    state: present
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0

- name: Get the security group info
  ec2_group_facts:
    region: "{{ region }}"
    filters:
      group-name: "{{ sg_name }}"
  register: sg_info

#- debug: var=sg_info

- name: Create AWS instances
  ec2:
    count_tag: 
      Name: "{{ ec2_name }}"
    exact_count: "{{ no_instances }}"
    group: "{{ sg_name }}"
    image: "{{ami_results.images[0].image_id}}"
    instance_tags:
      Name: "{{ ec2_name }}"
    instance_type: "{{ instance_type }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{subnet_ids.subnets[4].id}}" 
